"""generate person model

Revision ID: 2ce57e21d87c
Revises: fac11edd9da0
Create Date: 2023-08-15 12:09:12.510709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce57e21d87c'
down_revision = 'fac11edd9da0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('characteristics_id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characteristics_id'], ['characteristics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossier.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
