"""generate motive table

Revision ID: 392e1ab9d1dd
Revises: 83f2d143f616
Create Date: 2023-08-14 17:38:08.455858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392e1ab9d1dd'
down_revision = '83f2d143f616'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motive_ref'), 'motive', ['ref'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_motive_ref'), table_name='motive')
    op.drop_table('motive')
    # ### end Alembic commands ###
