"""return nullable fields

Revision ID: 682b35f709ce
Revises: a8fc466d6915
Create Date: 2023-08-15 17:30:39.722430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682b35f709ce'
down_revision = 'a8fc466d6915'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dossier_motive', 'motive_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('person', 'characteristics_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('person', 'dossier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('special_sign_in_characteristics', 'special_sign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('special_sign_in_characteristics', 'special_sign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('person', 'dossier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('person', 'characteristics_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dossier_motive', 'motive_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
