"""generate characteristics table

Revision ID: 83f2d143f616
Revises: 61d733c0f020
Create Date: 2023-08-14 17:05:13.057720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "83f2d143f616"
down_revision = "61d733c0f020"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characteristics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ref", sa.String(length=255), nullable=True),
        sa.Column("weight", sa.Float(precision=2), nullable=False),
        sa.Column("height", sa.Float(precision=2), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("sex", sa.Enum("MALE", "FEMAL", name="sex"), nullable=False),
        sa.Column("eyes_color", sa.String(length=255), nullable=False),
        sa.Column("hairs_color", sa.String(length=255), nullable=False),
        sa.Column("nationality", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ref"),
    )
    op.create_table(
        "special_sign_in_characteristics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("characteristic_id", sa.Integer(), nullable=False),
        sa.Column("special_sign_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["characteristic_id"], ["characteristics.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["special_sign_id"], ["special_sign.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("special_sign_in_characteristics")
    op.drop_table("characteristics")
    sa.Enum("MALE", "FEMAL", name="sex").drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
