"""update nullable fields

Revision ID: 9a28cd21be36
Revises: fedfe6316b61
Create Date: 2023-08-15 13:36:10.867539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a28cd21be36'
down_revision = 'fedfe6316b61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hobby', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('motive', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('special_sign', 'ref',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('special_sign_in_characteristics', 'special_sign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('special_sign_in_characteristics', 'special_sign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('special_sign', 'ref',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('motive', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('hobby', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
