"""generate hobby table

Revision ID: e9c1bd19f367
Revises: 392e1ab9d1dd
Create Date: 2023-08-14 18:13:36.517098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c1bd19f367'
down_revision = '392e1ab9d1dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hobby',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hobby_ref'), 'hobby', ['ref'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hobby_ref'), table_name='hobby')
    op.drop_table('hobby')
    # ### end Alembic commands ###
