"""generate dossier table

Revision ID: fac11edd9da0
Revises: e9c1bd19f367
Create Date: 2023-08-14 18:45:38.452178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fac11edd9da0"
down_revision = "e9c1bd19f367"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dossier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ref", sa.String(length=255), nullable=False),
        sa.Column("history", sa.Text(), nullable=False),
        sa.Column(
            "social_status",
            sa.Enum("WORKS", "UNEMPLOYED", name="socialstatus"),
            nullable=False,
        ),
        sa.Column(
            "marriage_status",
            sa.Enum("MARRIED", "UNMARRIED", "DIVORCED", name="marriagestatus"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dossier_ref"), "dossier", ["ref"], unique=True)
    op.create_table(
        "dossier_hobby",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dossier_id", sa.Integer(), nullable=False),
        sa.Column("hobby_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dossier_id"], ["dossier.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["hobby_id"], ["hobby.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dossier_motive",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dossier_id", sa.Integer(), nullable=False),
        sa.Column("motive_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["dossier_id"], ["dossier.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["motive_id"], ["motive.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dossier_motive")
    op.drop_table("dossier_hobby")
    op.drop_index(op.f("ix_dossier_ref"), table_name="dossier")
    op.drop_table("dossier")
    sa.Enum("WORKS", "UNEMPLOYED", name="socialstatus").drop(
        op.get_bind(), checkfirst=True
    )
    sa.Enum("MARRIED", "UNMARRIED", "DIVORCED", name="marriagestatus").drop(
        op.get_bind(), checkfirst=True
    )
    # ### end Alembic commands ###
