"""generate criminal model

Revision ID: fedfe6316b61
Revises: 2ce57e21d87c
Create Date: 2023-08-15 12:46:31.207176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fedfe6316b61"
down_revision = "2ce57e21d87c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "criminal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column(
            "criminal_type",
            sa.Enum(
                "MARDER",
                "MANIAC",
                "POISONER",
                "STRANGLER",
                "DISMANTLER",
                "THIEF",
                name="criminaltype",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("criminal")
    sa.Enum(
        "MARDER",
        "MANIAC",
        "POISONER",
        "STRANGLER",
        "DISMANTLER",
        "THIEF",
        name="criminaltype",
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
